name: aqua
description: Utility classes/functions to help with UI development using the Flutter framework.
version: 1.2.5
homepage: https://github.com/therenca/aqua

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  intl: ^0.19.0
  colorize: ^3.0.0
  collection: ^1.15.0
  shared_preferences: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

